// setupPages.js
// Single source of truth for Salesforce Setup destinations, shared by the
// command palette (commandPalette.data.js) and the popup (popupCatalog.js).
// Loaded before both via the manifest content_scripts order and popup.html.
//
// Each entry is [label, url, category]. category feeds search keywords and
// disambiguates duplicate labels. Identifiers were taken from a live org's full
// Setup tree. A few legacy/renamed ones were corrected (Process Automation
// Settings, Sites/Custom URLs/Domains, CORS, Trusted URLs), and labels that
// would otherwise collide were qualified (e.g. "Skills (Service)").
(function () {
    "use strict";

    const S = (id) => `/lightning/setup/${id}/home`;

    const SETUP_PAGES = [
        // --- Setup / top ---
        ["Setup Home", S("SetupOneHome"), "Setup"],
        ["Object Manager", S("ObjectManager"), "Setup"],
        ["Salesforce Go", S("SalesforceGo"), "Setup"],
        ["Service Setup Assistant", S("ServiceHome"), "Setup"],
        ["Commerce Setup Assistant", S("CommerceSetupAssistant"), "Setup"],
        ["Hyperforce Assistant", S("HyperforceAssistant"), "Setup"],
        ["Release Updates", S("ReleaseUpdates"), "Setup"],
        ["Salesforce Mobile App", S("SalesforceMobileAppQuickStart"), "Setup"],
        ["Lightning Usage", S("LightningUsageSetup"), "Setup"],
        ["Optimizer", S("SalesforceOptimizer"), "Setup"],
        ["AgentExchange Offers", S("IsvTmOffersMarketplace"), "Setup"],
        ["Sales Cloud Everywhere", S("SalesCloudEverywhereSettings"), "Setup"],

        // --- Administration: Users ---
        ["Users", S("ManageUsers"), "Users"],
        ["Profiles", S("EnhancedProfiles"), "Users"],
        ["Permission Sets", S("PermSets"), "Users"],
        ["Permission Set Groups", S("PermSetGroups"), "Users"],
        ["Roles", S("Roles"), "Users"],
        ["Public Groups", S("PublicGroups"), "Users"],
        ["Queues", S("Queues"), "Users"],
        ["User Management Settings", S("UserManagementSettings"), "Users"],
        ["Analytics Groups", S("DataAnalyticsGroups"), "Users"],

        // --- Administration: Data ---
        ["Big Objects", S("BigObjects"), "Data"],
        ["Data Export", S("DataManagementExport"), "Data"],
        ["Data Integration Metrics", S("XCleanVitalsUi"), "Data"],
        ["Data Integration Rules", S("CleanRules"), "Data"],
        ["Duplicate Error Logs", S("DuplicateErrorLog"), "Data"],
        ["Duplicate Rules", S("DuplicateRules"), "Data"],
        ["Matching Rules", S("MatchingRules"), "Data"],
        ["Mass Delete Records", S("DataManagementDelete"), "Data"],
        ["Mass Transfer Approval Requests", S("DataManagementManageApprovals"), "Data"],
        ["Mass Transfer Records", S("DataManagementTransfer"), "Data"],
        ["Mass Update Addresses", S("DataManagementMassUpdateAddresses"), "Data"],
        ["Picklist Settings", S("PicklistSettings"), "Data"],
        ["Schema Settings", S("SchemaSettings"), "Data"],
        ["State and Country/Territory Picklists", S("AddressCleanerOverview"), "Data"],
        ["Storage Usage", S("CompanyResourceDisk"), "Data"],
        ["Field History Tracking", S("FieldHistoryTracking"), "Data"],

        // --- Email ---
        ["Apex Exception Email", S("ApexExceptionEmail"), "Email"],
        ["Authorized Email Domains", S("AuthorizedEmailDomains"), "Email"],
        ["Classic Email Templates", S("CommunicationTemplatesEmail"), "Email"],
        ["Classic Letterheads", S("CommunicationTemplatesLetterheads"), "Email"],
        ["Compliance BCC Email", S("SecurityComplianceBcc"), "Email"],
        ["DKIM Keys", S("EmailDKIMList"), "Email"],
        ["Delete Attachments Sent as Links", S("EmailAttachmentManagement"), "Email"],
        ["Deliverability", S("OrgEmailSettings"), "Email"],
        ["Email Address Internationalization", S("InternationalEmailAddresses"), "Email"],
        ["Email Attachments", S("EmailAttachmentSettings"), "Email"],
        ["Email Domain Filters", S("EmailDomainFilter"), "Email"],
        ["Email Relays", S("EmailRelay"), "Email"],
        ["Email Footers", S("EmailDisclaimers"), "Email"],
        ["Email to Salesforce", S("EmailToSalesforce"), "Email"],
        ["Enhanced Email", S("EnhancedEmail"), "Email"],
        ["Filter Email Tracking", S("FilterEmailTracking"), "Email"],
        ["Gmail Integration and Sync", S("LightningForGmailAndSyncSettings"), "Email"],
        ["Lightning Email Templates", S("LightningEmailTemplateSetup"), "Email"],
        ["Mail Merge Templates", S("CommunicationTemplatesWord"), "Email"],
        ["Organization-Wide Addresses", S("OrgWideEmailAddresses"), "Email"],
        ["Outlook Integration and Sync", S("LightningForOutlookAndSyncSettings"), "Email"],
        ["Send through External Email Services", S("EmailTransportServiceSetupPage"), "Email"],
        ["Test Deliverability", S("TestEmailDeliverability"), "Email"],

        // --- Apps ---
        ["App Manager", S("NavigationMenus"), "Apps"],
        ["AppExchange Marketplace", S("AppExchangeMarketplace"), "Apps"],
        ["Connected Apps OAuth Usage", S("ConnectedAppsUsage"), "Apps"],
        ["Manage Connected Apps", S("ConnectedApplication"), "Apps"],
        ["External Client App Manager", S("ManageExternalClientApplication"), "Apps"],
        ["External Client App OAuth Usage", S("ExternalClientApplicationOauthUsage"), "Apps"],
        ["External Client App Settings", S("ExternalClientApplicationSettings"), "Apps"],
        ["App Hub", S("AppHub"), "Apps"],
        ["App Templates (Template Studio)", S("TemplateStudio"), "Apps"],
        ["Flow Category", S("FlowCategory"), "Apps"],
        ["Lightning Bolt Solutions", S("LightningBolt"), "Apps"],
        ["Lightning Out 2.0 App Manager", S("LightningOut"), "Apps"],
        ["Mobile Security", S("MobileSecurity"), "Apps"],
        ["Mobile Builder (Seller-Focused)", S("SalesCloudMab"), "Apps"],
        ["Salesforce Branding", S("Salesforce1Branding"), "Apps"],
        ["Salesforce Navigation", S("ProjectOneAppMenu"), "Apps"],
        ["Salesforce Notifications", S("NotificationsSettings"), "Apps"],
        ["Salesforce Offline", S("MobileOfflineStorageAdmin"), "Apps"],
        ["Salesforce Settings", S("Salesforce1Settings"), "Apps"],
        ["Installed Packages", S("ImportedPackage"), "Apps"],
        ["Package Manager", S("Package"), "Apps"],
        ["Package Usage", S("PackageUsageSummary"), "Apps"],
        ["App Install History", S("InsightsSetupAppHistoryControlPanel"), "Apps"],
        ["Auto-Installed Apps", S("InsightsSetupAutoInstalledApps"), "Apps"],

        // --- Analytics (Reports & Dashboards) ---
        ["Analytics Access Policies", S("SessionLevelPolicyUI"), "Analytics"],
        ["Historical Trending", S("HistoricalTrendingUI"), "Analytics"],
        ["Report Types", S("CustomReportTypeLightning"), "Analytics"],
        ["Reporting Snapshots", S("AnalyticSnapshots"), "Analytics"],
        ["Reports and Dashboards Settings", S("ReportUI"), "Analytics"],
        ["Tableau Embedding", S("TableauEmbeddingSettings"), "Analytics"],
        ["Tableau UAF Claims Definition", S("TableauUafClaimDefnSettings"), "Analytics"],

        // --- Chatter / Collaboration ---
        ["Approval Settings", S("ApprovalSetup"), "Chatter"],
        ["Chatter Settings", S("CollaborationSettings"), "Chatter"],
        ["Chatter Email Settings", S("ChatterEmailSettings"), "Chatter"],
        ["Feed Item Actions", S("FeedItemActions"), "Chatter"],
        ["Feed Item Layouts", S("FeedItemLayouts"), "Chatter"],
        ["Feed Tracking", S("FeedTracking"), "Chatter"],
        ["Group Layouts", S("CollaborationGroupLayouts"), "Chatter"],
        ["Group Member Triggers", S("CollaborationGroupMemberTriggers"), "Chatter"],
        ["Group Record Triggers", S("CollaborationGroupRecordTriggers"), "Chatter"],
        ["Group Triggers", S("CollaborationGroupTriggers"), "Chatter"],
        ["Group Record Types", S("CollaborationGroupRecordTypes"), "Chatter"],
        ["Chatter Influence", S("InfluenceSettings"), "Chatter"],
        ["FeedComment Triggers", S("FeedCommentTriggers"), "Chatter"],
        ["FeedItem Triggers", S("FeedItemTriggers"), "Chatter"],

        // --- Commerce / Communities / Misc ---
        ["Commerce Settings", S("CommerceStoreEnable"), "Commerce"],
        ["B2C Commerce Connections", S("ManageC2CSelfProvisioningConnections"), "Commerce"],
        ["Licenses & Limits", S("ViewLicensesAndLimits"), "Company"],
        ["Prospector Preferences", S("DataDotComPreferences"), "Data"],
        ["Prospector Users", S("ProspectingUsers"), "Data"],
        ["All Sites", S("SetupNetworks"), "Communities"],
        ["Experience Pages", S("CommunityFlexiPageList"), "Communities"],
        ["Salesforce CMS", S("SalesforceCMSSettings"), "Communities"],
        ["Network Settings", S("NetworkSettings"), "Communities"],
        ["Experience Templates", S("CommunityTemplateDefinitionList"), "Communities"],
        ["Experience Themes", S("CommunityThemeDefinitionList"), "Communities"],
        ["Functions", S("Functions"), "Communities"],
        ["Experience Home", S("Home"), "Communities"],

        // --- Marketing / Leads ---
        ["Accounts As Campaign Members", S("AccountAsCM"), "Marketing"],
        ["Auto-Association Settings", S("AutoAssociationSettings"), "Marketing"],
        ["Campaign Influence Settings", S("CampaignInfluenceSettings"), "Marketing"],
        ["Lead Assignment Rules", S("LeadRules"), "Leads"],
        ["Lead Auto-Response Rules", S("LeadResponses"), "Leads"],
        ["Lead Processes", S("LeadProcess"), "Leads"],
        ["Lead Settings", S("LeadSettings"), "Leads"],
        ["Lead Gen Fields", S("LinkedInLeadGenFields"), "Leads"],
        ["LinkedIn Accounts", S("LinkedInLeadGenAccounts"), "Leads"],
        ["Web-to-Lead", S("LeadWebtoleads"), "Leads"],
        ["Omnichannel Inventory", S("OmniChannelInventory"), "Marketing"],
        ["Payments", S("PaymentsSettings"), "Marketing"],
        ["Quip (Salesforce Anywhere)", S("SalesforceAnywhereSetupPage"), "Marketing"],

        // --- Sales ---
        ["Account Settings", S("AccountSettings"), "Sales"],
        ["Account Teams", S("AccountTeamSelling"), "Sales"],
        ["Person Accounts", S("PersonAccountSettings"), "Sales"],
        ["Activity Settings", S("HomeActivitiesSetupPage"), "Sales"],
        ["Contact Intelligence View Setup", S("ContactInspectionSettings"), "Sales"],
        ["Contact Roles on Contracts", S("ContractContactRoles"), "Sales"],
        ["Contact Roles on Opportunities", S("OpportunityRoles"), "Sales"],
        ["Contract Settings", S("ContractSettings"), "Sales"],
        ["Forecasts Hierarchy", S("Forecasting3Role"), "Sales"],
        ["Forecasts Settings", S("Forecasting3Settings"), "Sales"],
        ["Individual Settings", S("IndividualSettings"), "Sales"],
        ["Lead Intelligence View Setup", S("LeadInspectionSettings"), "Sales"],
        ["LinkedIn Sales Navigator", S("LinkedInSalesNavigatorPage"), "Sales"],
        ["Salesforce Meetings Settings", S("SalesforceMeetingsSettings"), "Sales"],
        ["Notes Settings", S("NotesSetupPage"), "Sales"],
        ["Big Deal Alert", S("OpportunityAlerts"), "Sales"],
        ["Opportunity Settings", S("OpportunitySettings"), "Sales"],
        ["Opportunity Team Settings", S("OpportunityTeamMemberSettings"), "Sales"],
        ["Order Settings", S("OrderSettings"), "Sales"],
        ["An Overview of PRM", S("PrmUnifiedSetupSettings"), "Sales"],
        ["Channel Management", S("ChannelManagement"), "Sales"],
        ["Partner Experience", S("PartnerExperience"), "Sales"],
        ["Partner Productivity", S("ChannelProductivity"), "Sales"],
        ["Asset Settings", S("AssetSettings"), "Sales"],
        ["Product Schedules Settings", S("Product2ScheduleSetup"), "Sales"],
        ["Product Settings", S("Product2Settings"), "Sales"],
        ["Quote Templates", S("QuoteTemplateEditor"), "Sales"],
        ["Quotes Settings", S("QuoteSettings"), "Sales"],
        ["Setup Assistant (EmailIQ)", S("EmailIqSetupPage"), "Sales"],
        ["Log a Call", S("DialerLogACallSetup"), "Sales"],
        ["Sales Engagement Settings", S("SalesEngagement"), "Sales"],
        ["Sales Processes", S("OpportunityProcess"), "Sales"],
        ["Territory Models", S("Territory2Models"), "Sales"],
        ["Territory Settings", S("Territory2Settings"), "Sales"],
        ["Territory Types", S("Territory2Types"), "Sales"],
        ["Update Reminders", S("OpportunityUpdateReminders"), "Sales"],

        // --- Salesforce Files ---
        ["Asset Files", S("ContentAssets"), "Files"],
        ["Content Deliveries and Public Links", S("ContentDistribution"), "Files"],
        ["Files Connect", S("ContentHub"), "Files"],
        ["Files: General Settings", S("FilesGeneralSettings"), "Files"],
        ["Regenerate Previews", S("RegeneratePreviews"), "Files"],
        ["Salesforce CRM Content", S("SalesforceCRMContent"), "Files"],

        // --- Salesforce Scheduler ---
        ["Assignment Policies", S("AppointmentAssignmentPolicy"), "Scheduler"],
        ["Salesforce Scheduler Settings", S("LightningSchedulerSettings"), "Scheduler"],
        ["Scheduling Policies", S("AppointmentSchedulingPolicy"), "Scheduler"],
        ["Skills (Scheduler)", S("Skills"), "Scheduler"],
        ["Scheduler Troubleshooter", S("SalesforceSchedulerTroubleshooting"), "Scheduler"],

        // --- Service ---
        ["Call Centers", S("CallCenters"), "Service"],
        ["Directory Numbers", S("AdditionalDirectoryNumbers"), "Service"],
        ["Softphone Layouts", S("SoftphoneLayouts"), "Service"],
        ["Case Assignment Rules", S("CaseRules"), "Service"],
        ["Case Auto-Response Rules", S("CaseResponses"), "Service"],
        ["Case Comment Triggers", S("CaseCommentTriggers"), "Service"],
        ["Case Merge", S("CaseMerge"), "Service"],
        ["Case Team Roles", S("CaseTeamRoles"), "Service"],
        ["Predefined Case Teams", S("CaseTeamTemplates"), "Service"],
        ["Chat Settings", S("LiveAgentSettings"), "Service"],
        ["Contact Roles on Cases", S("CaseContactRoles"), "Service"],
        ["Conversation Intelligence Rules", S("CiSignals"), "Service"],
        ["Conversation Service APIs", S("ConversationServiceAPI"), "Service"],
        ["Customer Contact Requests", S("ContactRequestFlows"), "Service"],
        ["Customer Service Incident Management", S("IncidentManagement"), "Service"],
        ["Email-to-Case", S("EmailToCase"), "Service"],
        ["Channel Menu", S("ChannelMenuDeployments"), "Service"],
        ["Embedded Service Deployments", S("EmbeddedServiceDeployments"), "Service"],
        ["Enhanced Chat User Verification", S("Authorization"), "Service"],
        ["Legacy Web Chat Migration (Beta)", S("MigrateChatDeployments"), "Service"],
        ["Entitlement Processes", S("SlaProcess"), "Service"],
        ["Entitlement Settings", S("EntitlementSettings"), "Service"],
        ["Entitlement Templates", S("EntitlementTemplates"), "Service"],
        ["Milestones", S("MilestoneTypes"), "Service"],
        ["Escalation Rules", S("CaseEscRules"), "Service"],
        ["Feed Filters", S("FeedFilterDefinitions"), "Service"],
        ["Field Service Mobile App Builder", S("FieldServiceAppBuilder"), "Service"],
        ["Field Service Settings", S("FieldServiceSettings"), "Service"],
        ["Macro Settings", S("MacroSettings"), "Service"],
        ["Messaging Components", S("ConversationMessageDefinitions"), "Service"],
        ["Messaging Settings", S("LiveMessageSetup"), "Service"],
        ["Omni-Channel Settings", S("OmniChannelSettings"), "Service"],
        ["Sensitive Data Rules for Enhanced Channels", S("MessagingSensitiveDataRulesEnhanced"), "Service"],
        ["Real-Time Translations", S("EinsteinConversationTranslate"), "Service"],
        ["Support Processes", S("CaseProcess"), "Service"],
        ["Support Settings", S("CaseSettings"), "Service"],
        ["Swarming", S("CaseSwarming"), "Service"],
        ["Web-to-Case", S("CaseWebtocase"), "Service"],
        ["Web-to-Case HTML Generator", S("CaseWebToCaseHtmlGenerator"), "Service"],
        ["Skill Types", S("SkillType"), "Service"],
        ["Skills (Service)", S("SkillPage"), "Service"],
        ["Survey Settings", S("SurveySettings"), "Service"],
        ["Topic Assignment Triggers", S("TopicAssigmentTriggers"), "Service"],
        ["Topic Triggers", S("TopicTriggers"), "Service"],
        ["Topics for Objects", S("TopicRecords"), "Service"],

        // --- Slack ---
        ["Manage Slack Connection", S("SlackWorkspaces"), "Slack"],
        ["Slack Apps Setup", S("SlackSetupAssistant"), "Slack"],
        ["Slack Channels for Records", S("SlackRecordChannels"), "Slack"],

        // --- Data Cloud / Heroku / MuleSoft ---
        ["Data Cloud Setup Home", S("CdpNoLicense"), "Data Cloud"],
        ["About Heroku", S("AboutHeroku"), "Heroku"],
        ["Heroku Apps", S("HerokuApps"), "Heroku"],
        ["Anypoint Platform Setup", S("MulesoftSetup"), "MuleSoft"],
        ["Integration Intelligence Setup Assistant", S("IntegrationIntelligence"), "MuleSoft"],
        ["MuleSoft Observability", S("MulesoftObservability"), "MuleSoft"],

        // --- Einstein / Search ---
        ["Agentforce Protection Policies", S("AgentforceProtectionPolicies"), "Einstein"],
        ["API Registry", S("ApiRegistry"), "Einstein"],
        ["Einstein Bots", S("EinsteinBots"), "Einstein"],
        ["Einstein.ai", S("EinsteinKeyManagement"), "Einstein"],
        ["Activity Sync Settings", S("ActivitySyncEngineSettingsMain"), "Einstein"],
        ["Promoted Search Terms", S("SearchPromotionRulesManagementPage"), "Search"],
        ["Search Layouts", S("EinsteinSearchLayouts"), "Search"],
        ["Search Analytics", S("SearchAnalytics"), "Search"],
        ["Query Configurations", S("SearchConfiguration"), "Search"],
        ["Search Setup", S("SearchIndex"), "Search"],
        ["Search Settings", S("EinsteinSearchSettings"), "Search"],
        ["Synonyms", S("ManageSynonyms"), "Search"],

        // --- Objects and Fields ---
        ["Picklist Value Sets", S("Picklists"), "Objects"],
        ["Schema Builder", S("SchemaBuilder"), "Objects"],

        // --- Events ---
        ["Event Manager", S("EventManager"), "Events"],
        ["Event Relays", S("EventRelay"), "Events"],
        ["Event Studio", S("EventHome"), "Events"],

        // --- Process Automation ---
        ["Flows", S("Flows"), "Automation"],
        ["Automation App", S("ProcessHome"), "Automation"],
        ["Approval Processes", S("ApprovalProcesses"), "Automation"],
        ["Process Automation Settings", S("WorkflowSettings"), "Automation"],
        ["Process Builder", S("ProcessAutomation"), "Automation"],
        ["Migrate to Flow", S("MigrateToFlowTool"), "Automation"],
        ["Next Best Action", S("NextBestAction"), "Automation"],
        ["Paused and Failed Flow Interviews", S("Pausedflows"), "Automation"],
        ["Post Templates", S("FeedTemplates"), "Automation"],
        ["Workflow Rules", S("WorkflowRules"), "Automation"],
        ["Email Alerts", S("WorkflowEmails"), "Automation"],
        ["Field Updates", S("WorkflowFieldUpdates"), "Automation"],
        ["Outbound Messages", S("WorkflowOutboundMessaging"), "Automation"],
        ["Send Actions", S("SendAction"), "Automation"],
        ["Workflow Tasks", S("WorkflowTasks"), "Automation"],

        // --- User Interface ---
        ["Action Link Templates", S("ActionLinkGroupTemplates"), "User Interface"],
        ["Actions & Recommendations", S("GuidedActions"), "User Interface"],
        ["App Menu", S("AppMenu"), "User Interface"],
        ["Console Workspace Page Loading Preference", S("DeferRenderingWorkspacePageSetupPage"), "User Interface"],
        ["Loaded Console Tab Limit", S("ConsoleMaxTabCacheSetup"), "User Interface"],
        ["Custom Labels", S("ExternalStrings"), "User Interface"],
        ["Density Settings", S("DensitySetup"), "User Interface"],
        ["Global Actions", S("GlobalActions"), "User Interface"],
        ["Publisher Layouts", S("GlobalPublisherLayouts"), "User Interface"],
        ["Lightning App Builder", S("FlexiPageList"), "User Interface"],
        ["Lightning Extension", S("LightningExtension"), "User Interface"],
        ["Path Settings", S("PathAssistantSetupHome"), "User Interface"],
        ["Quick Text Settings", S("LightningQuickTextSettings"), "User Interface"],
        ["Record Page Settings", S("SimpleRecordHome"), "User Interface"],
        ["Rename Tabs and Labels", S("RenameTab"), "User Interface"],
        ["Custom URLs", S("DomainSites"), "User Interface"],
        ["Domains", S("DomainNames"), "User Interface"],
        ["Sites", S("CustomDomain"), "User Interface"],
        ["Tabs", S("CustomTabs"), "User Interface"],
        ["Themes and Branding", S("ThemingAndBranding"), "User Interface"],
        ["Translation Export", S("LabelWorkbenchExport"), "User Interface"],
        ["Translation Import", S("LabelWorkbenchImport"), "User Interface"],
        ["Translation Override", S("LabelWorkbenchOverride"), "User Interface"],
        ["Translate", S("LabelWorkbenchTranslate"), "User Interface"],
        ["Translation Language Settings", S("LabelWorkbenchSetup"), "User Interface"],
        ["User Interface", S("UserInterfaceUI"), "User Interface"],

        // --- Custom Code ---
        ["Apex Classes", S("ApexClasses"), "Custom Code"],
        ["Apex Settings", S("ApexSettings"), "Custom Code"],
        ["Apex Triggers", S("ApexTriggers"), "Custom Code"],
        ["Apex Test Execution", S("ApexTestQueue"), "Custom Code"],
        ["Apex Test History", S("ApexTestHistory"), "Custom Code"],
        ["Canvas App Previewer", S("CanvasPreviewerUi"), "Custom Code"],
        ["Custom Metadata Types", S("CustomMetadata"), "Custom Code"],
        ["Custom Permissions", S("CustomPermissions"), "Custom Code"],
        ["Custom Settings", S("CustomSettings"), "Custom Code"],
        ["DataWeave Resources", S("DataWeaveResources"), "Custom Code"],
        ["Email Services", S("EmailToApexFunction"), "Custom Code"],
        ["Debug Mode", S("UserDebugModeSetup"), "Custom Code"],
        ["Lightning Components", S("LightningComponentBundles"), "Custom Code"],
        ["Local Dev", S("LightningPreview"), "Custom Code"],
        ["Lightning Types", S("LightningTypes"), "Custom Code"],
        ["Platform Cache", S("PlatformCache"), "Custom Code"],
        ["Remote Access", S("RemoteAccess"), "Custom Code"],
        ["Static Resources", S("StaticResources"), "Custom Code"],
        ["Dev Tools", S("ClientDevTools"), "Custom Code"],
        ["Visualforce Components", S("ApexComponents"), "Custom Code"],
        ["Visualforce Pages", S("ApexPages"), "Custom Code"],
        ["Developer Console", "/_ui/common/apex/debug/ApexCSIPage", "Custom Code"],

        // --- Development ---
        ["Agentforce Vibes Extension", S("EinsteinForDevelopers"), "Development"],
        ["Dev Hub", S("DevHub"), "Development"],
        ["DevOps Center", S("DevOpsCenterSetup"), "Development"],
        ["Scratch Orgs", S("ShapeGrantAccess"), "Development"],
        ["Web Console (Beta)", S("PlatformWebIdeSetup"), "Development"],

        // --- Scale ---
        ["Scale Center Overview", S("ScaleTestOverview"), "Scale"],

        // --- Environments (jobs, monitors, deployment) ---
        ["Deployment Settings", S("DeploymentSettings"), "Environments"],
        ["Deployment Status", S("DeployStatus"), "Environments"],
        ["Inbound Change Sets", S("InboundChangeSet"), "Environments"],
        ["Outbound Change Sets", S("OutboundChangeSet"), "Environments"],
        ["Apex Flex Queue", S("ApexFlexQueue"), "Environments"],
        ["Apex Jobs", S("AsyncApexJobs"), "Environments"],
        ["Background Jobs", S("ParallelJobsStatus"), "Environments"],
        ["Bulk Data Load Jobs", S("AsyncApiJobStatus"), "Environments"],
        ["Scheduled Jobs", S("ScheduledJobs"), "Environments"],
        ["Debug Logs", S("ApexDebugLogs"), "Environments"],
        ["Email Log Files", S("EmailLogFiles"), "Environments"],
        ["API Usage Notifications", S("MonitoringRateLimitingNotification"), "Environments"],
        ["Case Escalations (Monitor)", S("DataManagementManageCaseEscalation"), "Environments"],
        ["Email Snapshots", S("EmailCapture"), "Environments"],
        ["Entitlement Processes (Monitor)", S("DataManagementManageSlaProcess"), "Environments"],
        ["Outbound Messages (Monitor)", S("WorkflowOmStatus"), "Environments"],
        ["Time-Based Workflow", S("DataManagementManageWorkflowQueue"), "Environments"],
        ["System Overview", S("SystemOverview"), "Environments"],

        // --- User Engagement ---
        ["Adoption Assistance", S("AdoptionAssistance"), "User Engagement"],
        ["Guidance Center", S("LearningSetup"), "User Engagement"],
        ["Help Menu", S("HelpMenu"), "User Engagement"],
        ["In-App Guidance", S("Prompts"), "User Engagement"],

        // --- Enablement ---
        ["Enablement Lite Settings", S("EnablementLitePrograms"), "Enablement"],

        // --- Integrations ---
        ["API", S("WebServices"), "Integrations"],
        ["API Catalog", S("ApiCatalog"), "Integrations"],
        ["MCP Servers", S("McpServer"), "Integrations"],
        ["Change Data Capture", S("CdcObjectEnablement"), "Integrations"],
        ["Data Import Wizard", S("DataManagementDataImporter"), "Integrations"],
        ["Data Loader", S("DataLoader"), "Integrations"],
        ["Dataloader.io", S("DataLoaderIo"), "Integrations"],
        ["External Data Sources", S("ExternalDataSource"), "Integrations"],
        ["External Objects", S("ExternalObjects"), "Integrations"],
        ["External Services", S("ExternalServices"), "Integrations"],
        ["Named Query API", S("ApiNamedQuery"), "Integrations"],
        ["Platform Events", S("EventObjects"), "Integrations"],
        ["Teams Integration", S("MicrosoftTeamsIntegration"), "Integrations"],

        // --- Notification Builder ---
        ["Custom Notifications", S("CustomNotifications"), "Notifications"],
        ["Notification Delivery Settings", S("NotificationTypesManager"), "Notifications"],

        // --- Offline / Monitoring ---
        ["Briefcase Builder", S("Briefcase"), "Offline"],
        ["Solution Deployment Monitoring", S("SolutionMonitoring"), "Monitoring"],

        // --- Company Settings ---
        ["Business Hours", S("BusinessHours"), "Company"],
        ["Public Calendars and Resources", S("Calendars"), "Company"],
        ["Company Information", S("CompanyProfileInfo"), "Company"],
        ["Data Protection and Privacy", S("ConsentManagement"), "Company"],
        ["Fiscal Year", S("ForecastFiscalYear"), "Company"],
        ["Holidays", S("Holiday"), "Company"],
        ["Language Settings", S("LanguageSettings"), "Company"],
        ["My Domain", S("OrgDomain"), "Company"],

        // --- Data Classification ---
        ["Data Classification Download", S("DataClassificationDownload"), "Data Classification"],
        ["Data Classification Settings", S("DataClassificationSettings"), "Data Classification"],
        ["Data Classification Upload", S("DataClassificationUpload"), "Data Classification"],
        ["Consent Event Stream", S("ConsentEventStream"), "Data Classification"],

        // --- Data Mask ---
        ["Data Mask: Create with Einstein", S("DataMaskGptSetup"), "Data Mask"],

        // --- Identity ---
        ["Auth. Providers", S("AuthProviders"), "Identity"],
        ["Identity Connect", S("IdentityConnect"), "Identity"],
        ["Identity Provider", S("IdpPage"), "Identity"],
        ["Identity Provider Event Log", S("IdpErrorLog"), "Identity"],
        ["Identity Verification", S("IdentityVerification"), "Identity"],
        ["Identity Verification History", S("VerificationHistory"), "Identity"],
        ["Login Flows", S("LoginFlow"), "Identity"],
        ["Login History", S("OrgLoginHistory"), "Identity"],
        ["OAuth Custom Scopes", S("OauthCustomScope"), "Identity"],
        ["OAuth and OpenID Connect Settings", S("OauthOidcSettings"), "Identity"],
        ["Single Sign-On Settings", S("SingleSignOn"), "Identity"],
        ["Token Exchange Handlers", S("OauthTokenExchangeHandlers"), "Identity"],

        // --- Security ---
        ["Activations", S("ActivatedIpAddressAndClientBrowsersPage"), "Security"],
        ["CORS", S("CorsWhitelistEntries"), "Security"],
        ["Certificate and Key Management", S("CertificatesAndKeysManagement"), "Security"],
        ["Delegated Administration", S("DelegateGroups"), "Security"],
        ["Event Log File Browser", S("ElfBrowser"), "Security"],
        ["Event Monitoring Settings", S("EventMonitoringSetup"), "Security"],
        ["Transaction Security Policies", S("TransactionSecurityNew"), "Security"],
        ["Expire All Passwords", S("SecurityExpirePasswords"), "Security"],
        ["Field Accessibility", S("FieldAccessibility"), "Security"],
        ["File Upload and Download Security", S("FileTypeSetting"), "Security"],
        ["Guest User Sharing Rule Access Report", S("GuestUserAccessVerification"), "Security"],
        ["Health Check", S("HealthCheck"), "Security"],
        ["Login Access Policies", S("LoginAccessPolicies"), "Security"],
        ["Named Credentials", S("NamedCredential"), "Security"],
        ["Network Access", S("NetworkAccess"), "Security"],
        ["Password Policies", S("SecurityPolicies"), "Security"],
        ["Platform Encryption Settings", S("EncryptionAdvancedSettings"), "Security"],
        ["Encryption Key Management", S("PlatformEncryptionKeyManagement"), "Security"],
        ["Portal Health Check", S("PortalSecurityReport"), "Security"],
        ["Private Connect", S("PrivateConnect"), "Security"],
        ["Remote Site Settings", S("SecurityRemoteProxy"), "Security"],
        ["Session Management", S("SessionManagementPage"), "Security"],
        ["Session Settings", S("SecuritySession"), "Security"],
        ["Sharing Settings", S("SecuritySharing"), "Security"],
        ["Trusted URL and Browser Policy Violations", S("BrowserPolicyViolations"), "Security"],
        ["Trusted URLs", S("SecurityCspTrustedSite"), "Security"],
        ["Trusted URLs for Redirects", S("SecurityRedirectWhitelistUrl"), "Security"],
        ["View Setup Audit Trail", S("SecurityEvents"), "Security"],
    ];

    window.SFEN_SETUP_PAGES = SETUP_PAGES;
})();
